### ISSUE TITLE
improve bash website entry 

### ISSUE THREAD

**Issue by AlejandroxSalazar** [asrob-uc3m/tutoriales#19]
https://github.com/asrob-uc3m/tutoriales/blob/master/software/linux/bash.md

As a beginner at  ASROB i have thought in some improvements that could make easier the understanding of this tutorial  for new people  .
List of changes .
1. glossary
there are many technicalities , that should be explained for a better understanding of the tutorial 
2. shortcuts
As the tutorial is for people that has never worked with Linux  before , i think , explain Linux shortcuts could make the user feel more comfortable using Linux .

**Comment by jgvictores** [comment]
Yes, this is definitely a must-do.

1. Could you please give some/many example specific words? (it would be very helpful! :smile:)
2. Yes, we can include bash `tab` and `ctrl` combinations. Note that general linux shortcuts will be treated in#17

**Comment by PeterBowman** [comment]
Things like reverse search (CTRL+R) and the Linux copy-paste magic (mouse wheel button or SHIFT+INSERT) usually come up when working with newcomers. Those could be reflected in the tutorial as well.

**Comment by jgvictores** [comment]
1. `concatenate` explained at a2f515ab0cab156c76516341de8d7427a0a65205 
2. Done at 9c1f9b567bd7de267d517916aa45b8e8bb6dcf64

Closing issue, please open new issue with specific terms if required in the future!
