### ISSUE TITLE
Recomendar FreeCAD como herramienta de diseño 3D

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/tutoriales#5]
Recomendar FreeCAD como herramienta de diseño 3D. En principio, deberían de poderse evitar cosas como: https://github.com/asrob-uc3m/asroboturret/issues/1#issuecomment-346861052

**Comment by Siotma** [comment]
Desde que lo descubrí yo siempre lo hago 👍

**Comment by jgvictores** [comment]
> Desde que lo descubrí yo siempre lo hago 👍 

👍

**Comment by David-Estevez** [comment]
Por alusiones (https://github.com/asrob-uc3m/asroboturret/issues/1#issuecomment-346861052) y totalmente de buen rollo:

Yo también prefiero usar software libre siempre que se pueda.  Pero el caso que comentas es un caso de incompatibilidad de versiones que puede ocurrir incluso en software libre. Esto mismo pasó en su día en Kicad cuando cambiaron el workflow del programa.  Podías abrir archivos viejos en la nueva versión convirtiéndolos, pero una vez convertidos no lo podías abrir en una versión previa. Y pasa en cualquier programa al que añades features nuevas que no están en versiones anteriores. Si bien es cierto que al ser open source es más sencillo actualizarte a la última versión, si ocurre un fallo de comunicación como el de la issue que citas es posible que ese mismo fallo ocurra con software libre.

**Comment by jgvictores** [comment]
Totalmente de acuerdo: en el software libre también se rompe la compatibilidad hacia atrás.

La ventaja del software libre es que puedes instalar una determinada versión (para ser compatible con el trabajo de otra persona o equipo, con granularidad hasta un commit específico) sin tener que pelearte con licencias ni cracks.

**Comment by jgvictores** [comment]
Added at 4e04aeb, improved at 42bc9a9.
